name: Automated Version Bump

on:
  push:
    branches:
      - main  # This runs every time code is merged or pushed to main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write # Allows the workflow to push the edited pyproject.toml file
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches full history so it can read commit messages
          fetch-tags: true

      - name: Python Semantic Release
        uses: python-semantic-release/publish-action@v9.16.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
