name: Automated Version Bump

on:
  push:
    branches:
      - main

# Silences the Node 20 deprecation warning
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  bump-version:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Python Semantic Release
        uses: python-semantic-release/publish-action@v9.16.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
